//go:build ignore

// generate_screen reads a JSON UI screen definition and generates Go builder
// code that reproduces the same screen using the mcbeui control builders.
//
// Usage:
//
//	go run generate/generate_screen.go --input examples/pack_example/screen.json --output generated/my_screen.go --name MyScreen
//
// Or as a go:generate directive in any .go file:
//
//	//go:generate go run generate/generate_screen.go --input ui/my_screen.json --output generated/my_screen.go --name MyScreen
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
)

const tmpl = `// Code generated by go generate from {{.Input}}; DO NOT EDIT.
package {{.Package}}

import (
	"github.com/trippleawap/go-mcbe-ui/mcbeui/controls"
	"github.com/trippleawap/go-mcbe-ui/mcbeui/schema"
)

// {{.Name}}Screen builds the {{.Name}} screen from the original JSON definition.
func {{.Name}}Screen() *schema.Screen {
	s := schema.NewScreen("{{.Namespace}}")
	s.Root = *controls.NewScreen().
		ID({{.ID}}).
		Anchor(schema.{{.AnchorFrom}}).
		Size(schema.Raw({{.SizeX}}, {{.SizeY}})).
		Control()

{{- range .Controls }}
{{.}}
{{- end }}
	return s
}
`

type genData struct {
	Input      string
	Package    string
	Name       string
	Namespace  string
	ID         string
	AnchorFrom string
	SizeX      int
	SizeY      int
	Controls   []string
}

func main() {
	input := flag.String("input", "", "path to JSON screen definition")
	output := flag.String("output", "", "path to generated Go file")
	name := flag.String("name", "", "Go function name (defaults to filename stem)")
	package_ := flag.String("package", "generated", "Go package name")
	flag.Parse()

	if *input == "" || *output == "" {
		fmt.Fprintf(os.Stderr, "usage: generate_screen --input <file> --output <file> [--name <FuncName>] [--package <pkg>]\n")
		os.Exit(1)
	}

	data, err := os.ReadFile(*input)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read input: %v\n", err)
		os.Exit(1)
	}

	var ctrl struct {
		ID         string        `json:"id"`
		AnchorFrom string        `json:"anchor_from"`
		Size       []interface{} `json:"size"`
		Controls   []string      `json:"controls,omitempty"`
	}
	if err := json.Unmarshal(data, &ctrl); err != nil {
		fmt.Fprintf(os.Stderr, "parse JSON: %v\n", err)
		os.Exit(1)
	}

	genName := *name
	if genName == "" {
		base := strings.TrimSuffix(strings.TrimSuffix(*output, ".go"), "_test.go")
		genName = strings.Title(strings.ReplaceAll(base, "/", "_"))
	}

	sizeX := 0
	sizeY := 0
	if len(ctrl.Size) > 0 {
		if v, ok := ctrl.Size[0].(float64); ok {
			sizeX = int(v)
		}
	}
	if len(ctrl.Size) > 1 {
		if v, ok := ctrl.Size[1].(float64); ok {
			sizeY = int(v)
		}
	}

	controlLines := make([]string, 0, len(ctrl.Controls))
	for _, c := range ctrl.Controls {
		controlLines = append(controlLines, fmt.Sprintf("\t// TODO: add %s", c))
	}

	gd := genData{
		Input:      *input,
		Package:    *package_,
		Name:       genName,
		Namespace:  "my_addon",
		ID:         fmt.Sprintf("%q", ctrl.ID),
		AnchorFrom: strings.ToUpper(ctrl.AnchorFrom[:1]) + ctrl.AnchorFrom[1:],
		SizeX:      sizeX,
		SizeY:      sizeY,
		Controls:   controlLines,
	}

	t, err := template.New("screen").Parse(tmpl)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse template: %v\n", err)
		os.Exit(1)
	}

	var out bytes.Buffer
	if err := t.Execute(&out, gd); err != nil {
		fmt.Fprintf(os.Stderr, "execute template: %v\n", err)
		os.Exit(1)
	}

	src, err := format.Source(out.Bytes())
	if err != nil {
		src = out.Bytes()
	}

	if err := os.WriteFile(*output, src, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", *output)
}
